### PR TITLE
Added issue templates

### LINKED ISSUE #1: Creation of Issue Template
Issue templates should be added for bug fixes and feature requests. The addition of these templates will allow easy and efficient filing of issues.

### PR DESCRIPTION
**Pull request by Sharkaboi**
Fixes #1 
Added issue templates (bug report and feature request).

### CODE REVIEW

**Review by danishjamal104 — CHANGES_REQUESTED** [review]
@Sharkaboi add checklist before reporting a bug. It can be regarding the correct SDK level, Gradle version, build type, etc.

**Comment by Sharkaboi** [comment]
Will do and update asap :)

**Comment by Sharkaboi** [comment]
Hey
Updated the changes requested.
Please review :)

**Review by danishjamal104 — APPROVED** [review]
Looks fine to me. Once you get sufficient approval PR will be merged.
@technojam/app-development review the changes.

**Review by Sarthak2601 — APPROVED** [review]
LGTM. Thanks @Sharkaboi !

**Pull request merged**
