### PR TITLE
Fix #9 : Addition of wireframes.

### LINKED ISSUE #9: Add wireframes for the app in readme file
Add wireframes or samples so that we can have glimpse of the app.
[Reference Link](https://drive.google.com/drive/folders/1_lbkjVX4aQWgLpr4lxSshEu5-blwl3WB?usp=sharing)

### PR DESCRIPTION
**Pull request by SajidEqubal**
Fixes #9 
WireFrames with mobile frames view.

### CODE REVIEW

**Review by noman2002 — APPROVED** [review]

**Review by Sarthak2601 — CHANGES_REQUESTED** [review]
The changes look good to me but the PR doesn't. Please follow the PR template, provide some description and change the title of the PR to - `Fix #9 : Addition of wireframes. `

**Comment by Sarthak2601** [comment]
Also, what was the need to create a new PR when there was already one existing ?

**Comment by Sarthak2601** [comment]
@SajidEqubal Before requesting a review, please make sure that you've done all the requested changes. This kind of act wastes the time of the reviewer and is not appreciated.

**Review by Sarthak2601 — APPROVED** [review]
LGTM. Thanks @SajidEqubal! 
I'm going ahead and merging this so that we have an updated readme.

**Pull request merged**
